spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/datart?&allowMultiQueries=true
    username: root
    password: tl891203

  mail:
    host: smtp.163.com
    port: 465
    username: tianbaiwan116@163.com
    fromAddress: tianbaiwan116@163.com
    password: Tl891203
    senderName: 百万

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: 127.0.0.1
    port: 6379




server:
  port: 8080
  address: 127.0.0.1

datart:
  server:
    address: http://127.0.0.1:3000

  user:
    active:
      send-mail: true  # 注册用户时是否需要邮件验证激活

  security:
    token:
      secret: "d@a$t%a^r&a*t" #加密密钥
      timeout-min: 30  # 登录会话有效时长，单位：分钟。

  env:
    file-path: ${user.dir}/files # 服务端文件保存位置

  screenshot:
    timeout-seconds: 60
    webdriver-type: CHROME
    webdriver-path: /liangt

cacheImpl: datart.server.service.impl.RedisCacheImpl